import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import React from "react";
import RegisterForm from "@/app/components/forms/RegisterForm";
import ClientOnly from "@/app/components/ClientOnly";
import ToasterProvider from "@/app/providers/ToasterProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterForm />
        </ClientOnly>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
